### login
POST http://localhost:8091/api/access-tokens/from-login
Content-Type: application/json

{
    "login": "api-test@localhost.net",
    "password": "test"
}

### get articles
GET http://localhost:8091/api/articles-sync/pragmoon
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhcGktdGVzdEBsb2NhbGhvc3QubmV0IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTM4NzI1NS43MzA0ODczMDAsImlhdCI6MTc4MTMwMDg1NS43MzA0ODczMDAsInNjbyI6W119.YxRSX5opprYBD0CQIxWZbA6jaiWVxodfnm6hK6lJNYT6Ib1B0q6oz6hrFJVFPx6BNd2hoSQ4xQ5jxmnxnORimdQ8fPOVswEBcHKC4O-3iTAtX2ahEi4_TM19rw23XIFCCCgAMH9eywUuBbHgJvHSYT6oVDEn165hu8seuUyn0-mav0lGB7e5iqjqq-P2igfrzByI8_wQ2gkhiSpJsihA8wYBsqP8_y6NFiWWYT_xlRbtLeA9f5LhlPjah4zdorE688tztvnOLVb9VFnmm8cIIRvPp4kd0bg4Nk09tVxhmBFWwKz4HvpdX8GoQnqrP8L-xT-2zY4tVo5krFE6rxdMEA

### update sync date
PUT http://localhost:8091/api/articles-sync/pragmoon/last-synced
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhcGktdGVzdEBsb2NhbGhvc3QubmV0IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTM4NzI1NS43MzA0ODczMDAsImlhdCI6MTc4MTMwMDg1NS43MzA0ODczMDAsInNjbyI6W119.YxRSX5opprYBD0CQIxWZbA6jaiWVxodfnm6hK6lJNYT6Ib1B0q6oz6hrFJVFPx6BNd2hoSQ4xQ5jxmnxnORimdQ8fPOVswEBcHKC4O-3iTAtX2ahEi4_TM19rw23XIFCCCgAMH9eywUuBbHgJvHSYT6oVDEn165hu8seuUyn0-mav0lGB7e5iqjqq-P2igfrzByI8_wQ2gkhiSpJsihA8wYBsqP8_y6NFiWWYT_xlRbtLeA9f5LhlPjah4zdorE688tztvnOLVb9VFnmm8cIIRvPp4kd0bg4Nk09tVxhmBFWwKz4HvpdX8GoQnqrP8L-xT-2zY4tVo5krFE6rxdMEA

""
