### login
POST {{url}}/access-tokens/from-login
Content-Type: application/json

{
    "login": "{{login}}",
    "password": "{{password}}"
}

### get articles
GET {{url}}/articles-sync/pragmoon
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhcGktdGVzdEBsb2NhbGhvc3QubmV0IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTQ2MzY0Mi45Mzk3OTkzOTAsImlhdCI6MTc4MTM3NzI0Mi45Mzk3OTkwMDksInNjbyI6W119.j4ob7Fiju650ARGgKpacXBZIVTpajU2p675ZaFUIWfYTc_VfZCNnbOqkRBOLYAHdhfu6vKKvnu8-ItTEacGlWtRqg_i8j-Z1jPpilhPAEcEO6uJ1l9xl7LIIUI3eK2Gm9x-cPMSXnwq9BA2gFd7NJhIykTCRi4JpOt5NeumCW8ReVjwpvW9_60VUNVrp8FcfaoIyGQ0dJRoweWtMHjCE4NwOffMfy3va0WovTc9U55jvClgvLIviZCq9KXIDxItpwsMHF6T5H4pQId3CQc2taksvELdAfN38xWRACuVeL4ZplJPDJNJ-3gzfuVB72sPTK79fXIQOhGTJUxTDLWBubA

### update sync date
PUT http://localhost:8091/api/articles-sync/pragmoon/last-synced
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhcGktdGVzdEBsb2NhbGhvc3QubmV0IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTM4NzI1NS43MzA0ODczMDAsImlhdCI6MTc4MTMwMDg1NS43MzA0ODczMDAsInNjbyI6W119.YxRSX5opprYBD0CQIxWZbA6jaiWVxodfnm6hK6lJNYT6Ib1B0q6oz6hrFJVFPx6BNd2hoSQ4xQ5jxmnxnORimdQ8fPOVswEBcHKC4O-3iTAtX2ahEi4_TM19rw23XIFCCCgAMH9eywUuBbHgJvHSYT6oVDEn165hu8seuUyn0-mav0lGB7e5iqjqq-P2igfrzByI8_wQ2gkhiSpJsihA8wYBsqP8_y6NFiWWYT_xlRbtLeA9f5LhlPjah4zdorE688tztvnOLVb9VFnmm8cIIRvPp4kd0bg4Nk09tVxhmBFWwKz4HvpdX8GoQnqrP8L-xT-2zY4tVo5krFE6rxdMEA

""

### destination categories
GET {{url}}/articles-sync/pragmoon/categories
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhcGktdGVzdEBsb2NhbGhvc3QubmV0IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTUzMTUyMS43NjEzMDEyMDAsImlhdCI6MTc4MTQ0NTEyMS43NjEzMDEyMDAsInNjbyI6W119.oqQfHUa8VDeRw1tRcT2hoELpxCeyFt51sA0i14-P1JjZDyM9t2Pb7ToEcLrKjzpxQdm1xfJPy8or2So1_od_juRa0d53xnCd7U2YSXWzzP0OsRR0Wqg-s27LVp3etw4QK75W_N5NS8KOf7bZmDb6Gb9liLsrnIM3X4ufbhW7bfkijGhZHw8daZik3hHF9sjIlV68PxApWZQbHaS1KYc0bwRanrGn1nFSIim6pXbCaDsVZyA3yXhieVnlvew22XQwa56s9ViMFrvpfD8qAVKNLdPIGn7Y4dz-BNJigbEND0aU4T63EpvRok6GVaIe87OFSI5svl6_fKNwpctiBnCcuA

### update category
PUT {{url}}/articles-sync/pragmoon/category
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhcGktdGVzdEBsb2NhbGhvc3QubmV0IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTUzMTUyMS43NjEzMDEyMDAsImlhdCI6MTc4MTQ0NTEyMS43NjEzMDEyMDAsInNjbyI6W119.oqQfHUa8VDeRw1tRcT2hoELpxCeyFt51sA0i14-P1JjZDyM9t2Pb7ToEcLrKjzpxQdm1xfJPy8or2So1_od_juRa0d53xnCd7U2YSXWzzP0OsRR0Wqg-s27LVp3etw4QK75W_N5NS8KOf7bZmDb6Gb9liLsrnIM3X4ufbhW7bfkijGhZHw8daZik3hHF9sjIlV68PxApWZQbHaS1KYc0bwRanrGn1nFSIim6pXbCaDsVZyA3yXhieVnlvew22XQwa56s9ViMFrvpfD8qAVKNLdPIGn7Y4dz-BNJigbEND0aU4T63EpvRok6GVaIe87OFSI5svl6_fKNwpctiBnCcuA

{
    "name": "test category"
}

### article categories
GET {{url}}/articles-sync/article/1/categories
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhcGktdGVzdEBsb2NhbGhvc3QubmV0IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTUzMTUyMS43NjEzMDEyMDAsImlhdCI6MTc4MTQ0NTEyMS43NjEzMDEyMDAsInNjbyI6W119.oqQfHUa8VDeRw1tRcT2hoELpxCeyFt51sA0i14-P1JjZDyM9t2Pb7ToEcLrKjzpxQdm1xfJPy8or2So1_od_juRa0d53xnCd7U2YSXWzzP0OsRR0Wqg-s27LVp3etw4QK75W_N5NS8KOf7bZmDb6Gb9liLsrnIM3X4ufbhW7bfkijGhZHw8daZik3hHF9sjIlV68PxApWZQbHaS1KYc0bwRanrGn1nFSIim6pXbCaDsVZyA3yXhieVnlvew22XQwa56s9ViMFrvpfD8qAVKNLdPIGn7Y4dz-BNJigbEND0aU4T63EpvRok6GVaIe87OFSI5svl6_fKNwpctiBnCcuA
