### login
POST http://localhost:8090/api/access-tokens/from-login
Content-Type: application/json

{
    "login": "karel@zavadil.eu",
    "password": "EBIvHjo0nInWIZosqOgV"
}

### verify
GET http://localhost:8090/api/access-tokens/verify/eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJrYXJlbEB6YXZhZGlsLmV1IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTEzNTQ4OC4yMjUxOTU3MDAsImlhdCI6MTc4MTA0OTA4OC4yMjUxOTU3MDAsInNjbyI6W119.KuccjgatSd3acaNGm9Tx7rSw3o-D11OyMcNjeB6nr6O6XQaa7eF_FlqikdW8JHWN8fvJ8gWQ2mGg3cmpSzRZVJXI6fcilfo4KI-Z85qIlRC8w5zAqy-qiJVjfn1WEHx5hKfjP3f7ALmNYHWKW4Pl83JTLVf4Bupi9MLFHJcJywYBTgR0bY6o-454YPQT_GmQq3CRWLyVzLwWYV7QfBYFYkxmnyQoMnlEmGMuROPKs5T6ibM1UmbH9fHS13KtRIcR7K-sntM_8ubkxian2grHw8hGegjhXzJe1RLtNg6Fnh8GrH9sN5H4Pfjd4myUBdD0o0DTpMlkXdSciZblHS9zzQ

### renew
POST http://localhost:8090/api/access-tokens/renew
Content-Type: application/json

{
    "refreshToken": "eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJrYXJlbEB6YXZhZGlsLmV1IiwiaXNzIjoiT1BFTi1QVUJMSVNIRVIiLCJhdWQiOiJPUEVOLVBVQkxJU0hFUiIsImV4cCI6MTc4MTEzNTQ4OC4yMjUxOTU3MDAsImlhdCI6MTc4MTA0OTA4OC4yMjUxOTU3MDAsInNjbyI6W119.KuccjgatSd3acaNGm9Tx7rSw3o-D11OyMcNjeB6nr6O6XQaa7eF_FlqikdW8JHWN8fvJ8gWQ2mGg3cmpSzRZVJXI6fcilfo4KI-Z85qIlRC8w5zAqy-qiJVjfn1WEHx5hKfjP3f7ALmNYHWKW4Pl83JTLVf4Bupi9MLFHJcJywYBTgR0bY6o-454YPQT_GmQq3CRWLyVzLwWYV7QfBYFYkxmnyQoMnlEmGMuROPKs5T6ibM1UmbH9fHS13KtRIcR7K-sntM_8ubkxian2grHw8hGegjhXzJe1RLtNg6Fnh8GrH9sN5H4Pfjd4myUBdD0o0DTpMlkXdSciZblHS9zzQ"
}
