create type tp_sync_state AS ENUM ('Pending', 'Synced', 'Failed');
create cast	(varchar AS tp_sync_state) WITH INOUT AS IMPLICIT;

create type tp_user_role AS ENUM ('Admin', 'Editor', 'Guest');
create cast	(varchar AS tp_user_role) WITH INOUT AS IMPLICIT;

CREATE TABLE usr (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	email varchar(255) NOT NULL,
	oauth_subject varchar(255) NULL,
	is_active BOOLEAN NOT NULL DEFAULT false,
	sync_state tp_sync_state NOT NULL DEFAULT 'Pending',
	user_role tp_user_role NOT NULL DEFAULT 'Guest'
);

CREATE INDEX idx_user_email ON usr (email);
CREATE INDEX idx_user_sync_state ON usr (sync_state);

CREATE TABLE article (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	header varchar(255) NOT NULL,
	preview_text varchar(255) NULL,
	content_html text NULL,
	publish_date timestamp,
	owner_id int4 NOT NULL,
	CONSTRAINT fk_article_owner_user_id FOREIGN KEY (owner_id) REFERENCES usr(id) ON DELETE SET NULL,
	partner_id int4 NULL,
	CONSTRAINT fk_article_partner_user_id FOREIGN KEY (partner_id) REFERENCES usr(id) ON DELETE SET NULL
);

CREATE INDEX idx_article_last_updated_on ON article (last_updated_on DESC);
CREATE INDEX idx_article_owner ON article (owner_id);
CREATE INDEX idx_article_partner ON article (partner_id);

CREATE TABLE article_image (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	image_name varchar(255) NOT NULL,
	article_id int4 NOT NULL,
	CONSTRAINT fk_article_image_article_id FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_article_image_article_id ON article_image (article_id, image_name);

create type tp_article_history_action AS ENUM ('Create', 'Edit', 'GrantAccess', 'RevokeAccess', 'AddImage', 'RemoveImage');
create cast	(varchar AS tp_article_history_action) WITH INOUT AS IMPLICIT;

CREATE TABLE article_history (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	action tp_article_history_action NOT NULL DEFAULT 'Edit',
	content TEXT,
	article_id int4 NOT NULL,
	CONSTRAINT fk_article_history_article_id FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE,
	user_id int4 NOT NULL,
	CONSTRAINT fk_article_history_user_id FOREIGN KEY (user_id) REFERENCES usr(id) ON DELETE SET NULL
);

CREATE INDEX idx_article_history_article_id ON article_history (article_id);
CREATE INDEX idx_article_history_user_id ON article_history (user_id);

CREATE TABLE destination (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name" varchar(255) NOT NULL,
	header_level INT NOT NULL DEFAULT 2,
	preview_width_px INT NOT NULL DEFAULT 1000,
	preview_bg_color varchar(20) NOT NULL DEFAULT '#ffffff',
	preview_text_color varchar(20) NOT NULL DEFAULT '#000000',
	preview_link_color varchar(20) NOT NULL DEFAULT '#000000',
	preview_font_family varchar(255) NOT NULL DEFAULT 'Times New Roman'
);

CREATE TABLE article_destination (
	article_id int4 NOT NULL,
	destination_id int4 NOT NULL,
	CONSTRAINT article_destination_pkey PRIMARY KEY (destination_id, article_id),
	CONSTRAINT fk_article_destination_article_id FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE,
	CONSTRAINT fk_article_destination_destination_id FOREIGN KEY (destination_id) REFERENCES destination(id) ON DELETE CASCADE
);
