CREATE TABLE category (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name" varchar(255) NOT NULL,
	destination_id int4 NOT NULL,
	CONSTRAINT fk_article_category_destination_id FOREIGN KEY (destination_id) REFERENCES destination(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_article_category_destination_id ON category (destination_id, "name");

CREATE TABLE article_category (
	article_id int4 NOT NULL,
	category_id int4 NOT NULL,
	CONSTRAINT article_destination_pkey PRIMARY KEY (article_id, category_id),
	CONSTRAINT fk_article_category_article_id FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE,
	CONSTRAINT fk_article_category_destination_id FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);
